Repository MIL-LO/ollim-api, pull requests merged in 2025-04, with the labels that each got.

#7 fix: .env 파일을 활용한 환경 변수 관리 기능 수정 및 Sentry 연동 개선
  admin-api/build.gradle.kts
  admin-api/src/main/resources/application.yml
  admin-api/src/test/kotlin/com/millo/ollim/admin/SentryIntegrationTest.kt
  app-api/build.gradle.kts
  app-api/src/main/resources/application.yml
  app-api/src/test/kotlin/com/millo/ollim/app/SentryIntegrationTest.kt
  core/src/main/resources/application.yml
Labels: ⚙ Setting, ✅ Test

#10 ci: dev, main 브랜치에 PR동작 시, gradle 기반 빌드 테스트 환경 세팅
  .github/workflows/ci.yml
  LICENSE
Labels: ⚙ Setting, ✅ Test, 🌏 Deploy

#15 feat: PostgreSQL, Redis, MongoDB 연동 설정 및 테스트 구성
  admin-api/build.gradle.kts
  app-api/build.gradle.kts
  app-api/src/main/kotlin/com/millo/ollim/app/AppApplication.kt
  app-api/src/main/kotlin/com/millo/ollim/app/controller/TestMongoController.kt
  app-api/src/main/kotlin/com/millo/ollim/app/controller/TestRedisController.kt
  app-api/src/main/resources/application.yml
  core/build.gradle.kts
  core/src/main/kotlin/com/millo/ollim/core/domain/dummy/DummyEntity.kt
  core/src/main/kotlin/com/millo/ollim/core/domain/dummy/DummyRepository.kt
  core/src/main/kotlin/com/millo/ollim/core/domain/test/TestDocument.kt
  core/src/main/kotlin/com/millo/ollim/core/domain/test/TestDocumentRepository.kt
  infrastructure/build.gradle.kts
  infrastructure/src/main/kotlin/com/millo/ollim/infrastructure/config/MongoConfig.kt
  infrastructure/src/main/kotlin/com/millo/ollim/infrastructure/config/RedisConfig.kt
  infrastructure/src/main/kotlin/com/millo/ollim/infrastructure/mongo/TestMongoService.kt
  infrastructure/src/main/kotlin/com/millo/ollim/infrastructure/redis/RedisService.kt
  infrastructure/src/main/resources/application.properties
  infrastructure/src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature
