Repository MIL-LO/ollim-api, pull requests merged in 2025-05, with the labels that each got.

#29 feat: 로그인 및 회원가입 (JWT Redis 키 정책 포함)
  .dockerignore
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle.kts
  docker-compose.yml
  prometheus.yml
  src/main/kotlin/com/millo/ollim/Application.kt
  src/main/kotlin/com/millo/ollim/auth/controller/AuthController.kt
  src/main/kotlin/com/millo/ollim/auth/domain/UserPrincipal.kt
  src/main/kotlin/com/millo/ollim/auth/dto/AppleUserInfo.kt
  src/main/kotlin/com/millo/ollim/auth/dto/GoogleUserInfo.kt
  src/main/kotlin/com/millo/ollim/auth/dto/OAuthUserInfo.kt
  src/main/kotlin/com/millo/ollim/auth/dto/TokenDTO.kt
  src/main/kotlin/com/millo/ollim/auth/service/AuthService.kt
  src/main/kotlin/com/millo/ollim/auth/service/AuthServiceImpl.kt
  src/main/kotlin/com/millo/ollim/auth/service/CustomOidcUserService.kt
  src/main/kotlin/com/millo/ollim/auth/service/RefreshTokenService.kt
  src/main/kotlin/com/millo/ollim/auth/service/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/millo/ollim/common/config/CorsConfig.kt
  src/main/kotlin/com/millo/ollim/common/config/JasyptConfig.kt
  src/main/kotlin/com/millo/ollim/common/config/RedisConfig.kt
  src/main/kotlin/com/millo/ollim/common/config/RestTemplateConfig.kt
  src/main/kotlin/com/millo/ollim/common/config/SecurityConfig.kt
  src/main/kotlin/com/millo/ollim/common/config/SwaggerConfig.kt
  src/main/kotlin/com/millo/ollim/common/config/SwaggerOAuthPropertyDecryptor.kt
  src/main/kotlin/com/millo/ollim/common/controller/EncryptionController.kt
  src/main/kotlin/com/millo/ollim/common/domain/BaseTimeEntity.kt
  src/main/kotlin/com/millo/ollim/common/util/AppleClientSecretInjector.kt
  src/main/kotlin/com/millo/ollim/common/util/AppleJwtGenerator.kt
  src/main/kotlin/com/millo/ollim/common/util/JwtAuthenticationFilter.kt
  src/main/kotlin/com/millo/ollim/common/util/JwtTokenProvider.kt
  src/main/kotlin/com/millo/ollim/common/util/OAuth2SuccessHandler.kt
  src/main/kotlin/com/millo/ollim/common/util/TokenExtractor.kt
  src/main/kotlin/com/millo/ollim/health/controller/HealthCheckController.kt
  src/main/kotlin/com/millo/ollim/health/controller/MongoHealthController.kt
  src/main/kotlin/com/millo/ollim/health/controller/RedisHealthController.kt
  src/main/kotlin/com/millo/ollim/health/domain/DummyDocument.kt
  src/main/kotlin/com/millo/ollim/health/domain/DummyEntity.kt
  src/main/kotlin/com/millo/ollim/health/repository/DummyDocumentRepository.kt
  src/main/kotlin/com/millo/ollim/health/repository/DummyRepository.kt
  src/main/kotlin/com/millo/ollim/health/service/MongoService.kt
  src/main/kotlin/com/millo/ollim/health/service/RedisService.kt
  src/main/kotlin/com/millo/ollim/user/domain/EmotionCharacterType.kt
  src/main/kotlin/com/millo/ollim/user/domain/ProviderType.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserEntity.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserOAuthEntity.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserProfileEntity.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserRole.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserStatus.kt
  src/main/kotlin/com/millo/ollim/user/dto/UserProfileDTO.kt
  src/main/kotlin/com/millo/ollim/user/repository/UserOAuthRepository.kt
  src/main/kotlin/com/millo/ollim/user/repository/UserProfileRepository.kt
  src/main/kotlin/com/millo/ollim/user/repository/UserRepository.kt
  src/main/kotlin/com/millo/ollim/user/service/UserProfileService.kt
  src/main/kotlin/com/millo/ollim/user/service/UserProfileServiceImpl.kt
  src/main/resources/application.yml
  src/test/kotlin/com/millo/ollim/common/util/JwtTokenProviderTest.kt
Labels: ✨ Feature, ✅ Test, 🔨 Refactor, 🐞 BugFix

#32 feat: 유저 관련 개선
  .github/workflows/cd.yml
  src/main/kotlin/com/millo/ollim/auth/controller/AuthController.kt
  src/main/kotlin/com/millo/ollim/auth/domain/UserPrincipal.kt
  src/main/kotlin/com/millo/ollim/auth/dto/AuthInfoDTO.kt
  src/main/kotlin/com/millo/ollim/auth/dto/TokenDTO.kt
  src/main/kotlin/com/millo/ollim/auth/service/AuthService.kt
  src/main/kotlin/com/millo/ollim/auth/service/AuthServiceImpl.kt
  src/main/kotlin/com/millo/ollim/auth/service/CustomOidcUserService.kt
  src/main/kotlin/com/millo/ollim/auth/service/RefreshTokenService.kt
  src/main/kotlin/com/millo/ollim/auth/service/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/millo/ollim/common/util/JwtTokenProvider.kt
  src/main/kotlin/com/millo/ollim/common/util/OAuth2SuccessHandler.kt
  src/main/kotlin/com/millo/ollim/user/controller/UserController.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserEntity.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserMBTI.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserProfileEntity.kt
  src/main/kotlin/com/millo/ollim/user/domain/UserStatus.kt
  src/main/kotlin/com/millo/ollim/user/dto/UserProfileDTO.kt
  src/main/kotlin/com/millo/ollim/user/service/NicknameService.kt
  src/main/kotlin/com/millo/ollim/user/service/NicknameServiceImpl.kt
  src/main/kotlin/com/millo/ollim/user/service/UserProfileService.kt
  src/main/kotlin/com/millo/ollim/user/service/UserProfileServiceImpl.kt
  src/main/resources/application.yml
  src/test/kotlin/com/millo/ollim/common/util/JwtTokenProviderTest.kt
Labels: ✨ Feature, 📬 API, 🐞 BugFix

#33 다이어리 CRUD, 로그 예시 기능 추가
  src/main/kotlin/com/millo/ollim/diary/controller/DiaryController.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryCollectionId.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryCollectionItems.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryCollections.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryContents.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryEmotions.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryEntries.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryEntryEmotionId.kt
  src/main/kotlin/com/millo/ollim/diary/domain/EmotionTags.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryCollectionItemsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryCollectionsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryContentsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryEmotionsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryEntriesRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/EmotionTagsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/request/CollectionRequest.kt
  src/main/kotlin/com/millo/ollim/diary/request/DiaryRequest.kt
  src/main/kotlin/com/millo/ollim/diary/request/TagRequest.kt
  src/main/kotlin/com/millo/ollim/diary/request/UpdateDiary.kt
  src/main/kotlin/com/millo/ollim/diary/response/DiaryResponse.kt
  src/main/kotlin/com/millo/ollim/diary/response/DiaryVO.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryCollectionItemsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryCollectionsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryContentsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryEmotionsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryEntriesService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryService.kt
  src/main/kotlin/com/millo/ollim/diary/service/EmotionTagsService.kt
  src/main/kotlin/com/millo/ollim/log/config/ActionLogsConfig.kt
  src/main/kotlin/com/millo/ollim/log/config/LogTestConfig.kt
  src/main/kotlin/com/millo/ollim/log/controller/LogController.kt
  src/main/kotlin/com/millo/ollim/log/domain/AdminActionLogs.kt
  src/main/kotlin/com/millo/ollim/log/service/LogTestService.kt
  src/test/kotlin/com/millo/ollim/log/LogControllerTest.kt
  src/test/kotlin/com/millo/ollim/log/LogTest.kt
Labels: ✨ Feature, 🔨 Refactor

#34 금칙어 기능 개발
  src/main/kotlin/com/millo/ollim/diary/controller/CollectionController.kt
  src/main/kotlin/com/millo/ollim/diary/controller/DiaryController.kt
  src/main/kotlin/com/millo/ollim/diary/controller/TagController.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryCollectionEntity.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryCollectionItemEntity.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryCollections.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryContentEntity.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryEmotionEntity.kt
  src/main/kotlin/com/millo/ollim/diary/domain/DiaryEntryEntity.kt
  src/main/kotlin/com/millo/ollim/diary/domain/EmotionTagEntity.kt
  src/main/kotlin/com/millo/ollim/diary/dto/CollectionDTO.kt
  src/main/kotlin/com/millo/ollim/diary/dto/DiaryDTO.kt
  src/main/kotlin/com/millo/ollim/diary/dto/TagDTO.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryCollectionItemsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryCollectionsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryContentsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryEmotionsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/DiaryEntriesRepository.kt
  src/main/kotlin/com/millo/ollim/diary/repository/EmotionTagsRepository.kt
  src/main/kotlin/com/millo/ollim/diary/request/CollectionRequest.kt
  src/main/kotlin/com/millo/ollim/diary/request/DiaryRequest.kt
  src/main/kotlin/com/millo/ollim/diary/request/TagRequest.kt
  src/main/kotlin/com/millo/ollim/diary/request/UpdateDiary.kt
  src/main/kotlin/com/millo/ollim/diary/response/DiaryResponse.kt
  src/main/kotlin/com/millo/ollim/diary/response/DiaryVO.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryCollectionItemsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryCollectionsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryContentsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryEmotionsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryEntriesService.kt
  src/main/kotlin/com/millo/ollim/diary/service/DiaryService.kt
  src/main/kotlin/com/millo/ollim/diary/service/EmotionTagsService.kt
  src/main/kotlin/com/millo/ollim/diary/service/impl/DiaryCollectionItemsServiceImpl.kt
  src/main/kotlin/com/millo/ollim/diary/service/impl/DiaryCollectionsServiceImpl.kt
  src/main/kotlin/com/millo/ollim/diary/service/impl/DiaryContentsServiceImpl.kt
  src/main/kotlin/com/millo/ollim/diary/service/impl/DiaryEmotionsServiceImpl.kt
  src/main/kotlin/com/millo/ollim/diary/service/impl/DiaryEntriesServiceImpl.kt
  src/main/kotlin/com/millo/ollim/diary/service/impl/DiaryServiceImpl.kt
  src/main/kotlin/com/millo/ollim/diary/service/impl/EmotionTagsServiceImpl.kt
  src/main/kotlin/com/millo/ollim/stopword/config/ProhibitedTrie.kt
  src/main/kotlin/com/millo/ollim/stopword/config/ProhibitedWordCache.kt
  src/main/kotlin/com/millo/ollim/stopword/config/ProhibitedWordCreator.kt
  src/main/kotlin/com/millo/ollim/stopword/controller/ProhibiteController.kt
  src/main/kotlin/com/millo/ollim/stopword/domain/ProhibitedWordEntity.kt
  src/main/kotlin/com/millo/ollim/stopword/repository/ProhibitedWordsRepository.kt
Labels: ✨ Feature
